### ISSUE TITLE
Action fails due to dubious ownership in repository

### ISSUE THREAD

**Issue by MatiasElo** [webispy/helloworld-docker-action#16]
Hi,

`checkpatch-action` has recently started failing for PRs to our repo (e.g. https://github.com/OpenDataPlane/odp/runs/7517155797?check_suite_focus=true#step:5:35) with a following error:

```
[1/4] Check commit - 7490dd5766e4f8d718506c3ad437b9ff5b221d6a
-------------------------------------------------------------
fatal: detected dubious ownership in repository at '/github/workspace'
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace

>> Success
```

I tried adding the exception in a previous step, but this doesn't seem to work (perhaps because `checkpatch-action` is run in a separate container). Any ideas how to work around this issue?

**Comment by webispy** [comment]
Thanks for reporting the issue.
As you may already know, after analyzing the cause, it appears that the checkpatch tool in docker container is running as root (uid `0`), but the owner of the `/github/workspace` directory is uid `1001`, which gives a fatal error regarding ownership.

I fixed it to work properly by handling `safe.directory` exception with `git` option instead of changing all workspace directory ownership.

You can check the log that works normally through https://github.com/webispy/checkpatch-action/runs/7535135717?check_suite_focus=true

**Comment by MatiasElo** [comment]
Thank you very much for the extremely fast fix!
